### ISSUE TITLE
wrong Block.Header.AppHash at morpheus-4001

### ISSUE THREAD

**Issue by kwunyeung** [desmos-labs/desmos#186]
I'm trying to sync a new full node from scratch but got `wrong Block.Header.AppHash` panic at height `10970`. Here is the stack trace.

```
Jun 01 21:12:15 cradle desmosd[103081]: I[2020-06-01|21:12:15.697] Committed state                              module=state height=10970 txs=1 appHash=15CFD9A7C81F7A6444CE40C3916378DF350CA97AF06C797F55E40E2369C84D35
Jun 01 21:12:15 cradle desmosd[103081]: panic: Failed to process committed block (10971:907E7276AA3D1CB846B419EE09F6A638C542ACA71906FD5EBB19A1B9DF966817): wrong Block.Header.AppHash.  Expected 15CFD9A7C81F7A6444CE40C3916378DF350CA97AF06C797F55E40E2369C84D35, got A44DA35D396A63218B979A0B94F8B8DFE815C931AE4D5FB356D3F63CCA579B89
Jun 01 21:12:15 cradle desmosd[103081]: goroutine 108 [running]:
Jun 01 21:12:15 cradle desmosd[103081]: github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).poolRoutine(0xc0016c8000)
Jun 01 21:12:15 cradle desmosd[103081]:         /home/ubuntu/go/pkg/mod/github.com/tendermint/tendermint@v0.33.3/blockchain/v0/reactor.go:344 +0x12ed
Jun 01 21:12:15 cradle desmosd[103081]: created by github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).OnStart
Jun 01 21:12:15 cradle desmosd[103081]:         /home/ubuntu/go/pkg/mod/github.com/tendermint/tendermint@v0.33.3/blockchain/v0/reactor.go:118 +0x84
Jun 01 21:12:15 cradle systemd[1]: desmosd.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
```
The tx is exactly the long poll Rooty has tested.

http://lcd.morpheus.desmos.network:1317/txs/AC8255952F11FA083AD17FF7B2BFE05136153A05FE2EF90DA406B8BCA14A43B2

I originally wanted to test syncing with `RocksDB` by cherry picking the commit. It failed at this height. Then I built the `v0.4.0` again and set it back to `goleveldb` but it stills get panic at the same height.

**Comment by RiccardoM** [comment]
I will close this as we never ran into it with the newer version. This was probably due to an incompatibility or different version of the software.
