### ISSUE TITLE
panic when run desmoscli keys add ${wallet_name}

### ISSUE THREAD

**Issue by CNSumi** [desmos-labs/desmos#232]
## Bug description
after make install, i run command `desmoscli keys add wallcn` but panic
```
root@pc4790:~/go# desmoscli keys add  wallcn
panic: No such interface “org.freedesktop.DBus.Properties” on object at path /

goroutine 1 [running]:
github.com/cosmos/cosmos-sdk/crypto/keys.keyringKeybase.writeInfo(0x1380398, 0x1380390, 0xc0005a0950, 0x1, 0x1, 0xc0005a0960, 0x1, 0x1, 0x150e9e0, 0xc000d937d0, ...)
	/root/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.38.5/crypto/keys/keyring.go:478 +0x38c
github.com/cosmos/cosmos-sdk/crypto/keys.keyringKeybase.writeLocalKey(0x1380398, 0x1380390, 0xc0005a0950, 0x1, 0x1, 0xc0005a0960, 0x1, 0x1, 0x150e9e0, 0xc000d937d0, ...)
	/root/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.38.5/crypto/keys/keyring.go:464 +0x189
github.com/cosmos/cosmos-sdk/crypto/keys.baseKeybase.CreateAccount(0x1380398, 0x1380390, 0xc0005a0950, 0x1, 0x1, 0xc0005a0960, 0x1, 0x1, 0x14fd220, 0xc0005b0690, ...)
	/root/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.38.5/crypto/keys/keybase_base.go:171 +0x192
github.com/cosmos/cosmos-sdk/crypto/keys.keyringKeybase.CreateAccount(...)
	/root/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.38.5/crypto/keys/keyring.go:106
github.com/cosmos/cosmos-sdk/client/keys.RunAddCmd(0xc000db5600, 0xc0012bbf70, 0x1, 0x1, 0x1522ac0, 0xc0005b0640, 0xc00068f8c0, 0xc000259c30, 0xb1b137)
	/root/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.38.5/client/keys/add.go:273 +0xa8b
github.com/cosmos/cosmos-sdk/client/keys.runAddCmd(0xc000db5600, 0xc0012bbf70, 0x1, 0x1, 0x0, 0x0)
	/root/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.38.5/client/keys/add.go:99 +0x166
github.com/spf13/cobra.(*Command).execute(0xc000db5600, 0xc0012bbf50, 0x1, 0x1, 0xc000db5600, 0xc0012bbf50)
	/root/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842 +0x453
github.com/spf13/cobra.(*Command).ExecuteC(0xc0001622c0, 0xbadbc0, 0xc0001622c0, 0x1158f8d)
	/root/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x349
github.com/spf13/cobra.(*Command).Execute(...)
	/root/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
github.com/tendermint/tendermint/libs/cli.Executor.Execute(0xc0001622c0, 0x1382de0, 0x2, 0xc0012c3e60)
	/root/go/pkg/mod/github.com/tendermint/tendermint@v0.33.6/libs/cli/setup.go:89 +0x3c
main.main()
	/root/go/src/github.com/desmos-labs/desmos/cmd/desmoscli/main.go:64 +0x392
```
my desmos version
```
root@pc4790:~/go# desmoscli version --long
name: Desmos
server_name: desmosd
client_name: desmoscli
version: 0.8.0-6-g60bddba
commit: 60bddba2ac92b52fcf7ed7a451dc2a7ee4b9a90b
build_tags: netgo ledger
go: go version go1.14.5 linux/amd64
```
my go enviroment
```
root@pc4790:~/go# go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/root/go"
GOPRIVATE=""
GOPROXY="https://goproxy.cn,direct"
GOROOT="/usr/local/golang/go1.14.5.linux-amd64"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/golang/go1.14.5.linux-amd64/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build554290394=/tmp/go-build -gno-record-gcc-switches"
```

## Steps to reproduce
desmoscli keys add  wallcn
 

## Expected behavior
expect create wallet

**Comment by CNSumi** [comment]
system info
```
root@pc4790:~/go# lsb_release  -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04 LTS
Release:	20.04
Codename:	focal
```

**Comment by CNSumi** [comment]
same error when i try create wallet at 
```
ubuntu 20.04 + v0.8.0
ubuntu 18.04 + v0.8.0
```

**Comment by kwunyeung** [comment]
@CNSumi thank you for reporting. Please try `v0.8.2`.

**Comment by CNSumi** [comment]
@kwunyeung 
same issue when i try `v0.8.2`
```
root@pc4790:~/projects/desmos# desmoscli version --long
name: Desmos
server_name: desmosd
client_name: desmoscli
version: 0.8.2
commit: 7d8c261272aba3692fe205d5e473cd469a814de1
build_tags: netgo ledger
go: go version go1.14.5 linux/amd64

root@pc4790:~/projects/desmos# desmoscli keys add  walletcn
panic: No such interface “org.freedesktop.DBus.Properties” on object at path /

goroutine 1 [running]:
github.com/cosmos/cosmos-sdk/crypto/keys.keyringKeybase.writeInfo(0x1380610, 0x1380608, 0xc000d88390, 0x1, 0x1, 0xc000d883a0, 0x1, 0x1, 0x150eb40, 0xc000d39e60, ...)
	/root/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.38.5/crypto/keys/keyring.go:478 +0x38c
github.com/cosmos/cosmos-sdk/crypto/keys.keyringKeybase.writeLocalKey(0x1380610, 0x1380608, 0xc000d88390, 0x1, 0x1, 0xc000d883a0, 0x1, 0x1, 0x150eb40, 0xc000d39e60, ...)
	/root/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.38.5/crypto/keys/keyring.go:464 +0x189
github.com/cosmos/cosmos-sdk/crypto/keys.baseKeybase.CreateAccount(0x1380610, 0x1380608, 0xc000d88390, 0x1, 0x1, 0xc000d883a0, 0x1, 0x1, 0x14fd3c0, 0xc0001c0af0, ...)
	/root/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.38.5/crypto/keys/keybase_base.go:171 +0x192
github.com/cosmos/cosmos-sdk/crypto/keys.keyringKeybase.CreateAccount(...)
	/root/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.38.5/crypto/keys/keyring.go:106
github.com/cosmos/cosmos-sdk/client/keys.RunAddCmd(0xc000d76b00, 0xc0000c7af0, 0x1, 0x1, 0x1522bc0, 0xc0001c0aa0, 0xc00062bce0, 0xc0006a7c30, 0xb1b137)
	/root/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.38.5/client/keys/add.go:273 +0xa8b
github.com/cosmos/cosmos-sdk/client/keys.runAddCmd(0xc000d76b00, 0xc0000c7af0, 0x1, 0x1, 0x0, 0x0)
	/root/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.38.5/client/keys/add.go:99 +0x166
github.com/spf13/cobra.(*Command).execute(0xc000d76b00, 0xc0000c7ad0, 0x1, 0x1, 0xc000d76b00, 0xc0000c7ad0)
	/root/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842 +0x453
github.com/spf13/cobra.(*Command).ExecuteC(0xc000125080, 0xbadbc0, 0xc000125080, 0x115928d)
	/root/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x349
github.com/spf13/cobra.(*Command).Execute(...)
	/root/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
github.com/tendermint/tendermint/libs/cli.Executor.Execute(0xc000125080, 0x13830b8, 0x2, 0xc000fdb3c0)
	/root/go/pkg/mod/github.com/tendermint/tendermint@v0.33.6/libs/cli/setup.go:89 +0x3c
main.main()
	/root/projects/desmos/cmd/desmoscli/main.go:64 +0x392
```

**Comment by RiccardoM** [comment]
Do you have `gnome-keyring` installed @CNSumi?

**Comment by CNSumi** [comment]
> Do you have `gnome-keyring` installed @CNSumi?

solved, it's a gnome-keyring bug
i use ubuntu 18.04 server lts now

**Comment by RiccardoM** [comment]
@CNSumi thanks for the feedback! I will close the issue :grin:
